name: internship-hunter
on:
  schedule:
    - cron: '5 12 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python agent.py
        env:
          SHEET_ENDPOINT: ${{ secrets.SHEET_ENDPOINT }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
